/**
 * Demo content for local development and the hosted demo.
 * Titles and venues are fictional. Posters are SVGs shipped with the client
 * under /posters, so the demo never depends on third-party image hosts.
 */

const users = [
  { name: 'Platform Admin', email: 'admin@bookmyshow.dev', password: 'Admin@123', role: 'admin' },
  { name: 'Ravi Kumar (Partner)', email: 'partner@bookmyshow.dev', password: 'Partner@123', role: 'partner' },
  { name: 'Meera Iyer (Partner)', email: 'partner2@bookmyshow.dev', password: 'Partner@123', role: 'partner' },
  { name: 'Ananya Sharma', email: 'user@bookmyshow.dev', password: 'User@1234', role: 'user' },
  { name: 'Karthik Reddy', email: 'karthik@bookmyshow.dev', password: 'User@1234', role: 'user' },
];

/** `releaseOffsetDays` is relative to today so "now showing" vs "upcoming" stays correct over time. */
const movies = [
  {
    title: 'Monsoon Express',
    slug: 'monsoon-express',
    description:
      'A disgraced railway cop gets one night to stop a heist aboard the Mumbai–Goa express before the monsoon floods cut the line.',
    durationMinutes: 148,
    genres: ['Action', 'Thriller'],
    languages: ['Hindi', 'Telugu'],
    releaseOffsetDays: -12,
    certificate: 'UA',
    director: 'Arjun Mehra',
    cast: ['Vikram Rao', 'Isha Kapoor', 'Danish Ali'],
  },
  {
    title: 'The Last Lighthouse',
    slug: 'the-last-lighthouse',
    description:
      'On a storm-battered island, a lighthouse keeper and a stranded journalist uncover what the sea has been hiding for forty years.',
    durationMinutes: 124,
    genres: ['Drama', 'Mystery'],
    languages: ['English'],
    releaseOffsetDays: -20,
    certificate: 'UA',
    director: 'Clara Whitfield',
    cast: ['Owen Hart', 'Priya Nair'],
  },
  {
    title: 'Kaalam',
    slug: 'kaalam',
    description:
      'A physicist in Hyderabad receives messages from her future self — each one warning her about a choice she has not made yet.',
    durationMinutes: 156,
    genres: ['Sci-Fi', 'Thriller'],
    languages: ['Telugu', 'Tamil', 'Hindi'],
    releaseOffsetDays: -5,
    certificate: 'UA',
    director: 'S. Raghavan',
    cast: ['Lakshmi Menon', 'Arvind Sundar', 'Rohit Varma'],
  },
  {
    title: 'Laugh Riot 2',
    slug: 'laugh-riot-2',
    description:
      'The chaotic Bansal family is back — this time hosting three weddings, one goat and zero budget in a single weekend.',
    durationMinutes: 132,
    genres: ['Comedy', 'Family'],
    languages: ['Hindi'],
    releaseOffsetDays: -30,
    certificate: 'U',
    director: 'Neha Bansal',
    cast: ['Raj Malhotra', 'Pooja Sethi', 'Kunal Joshi'],
  },
  {
    title: 'Starbound',
    slug: 'starbound',
    description:
      'Humanity’s first interstellar crew wakes up 200 years early — and finds that someone else is already on board.',
    durationMinutes: 165,
    genres: ['Sci-Fi', 'Adventure'],
    languages: ['English', 'Hindi'],
    releaseOffsetDays: -8,
    certificate: 'UA',
    director: 'Marcus Lee',
    cast: ['Hannah Cole', 'Dev Malhotra', 'Ade Okafor'],
  },
  {
    title: 'Rangoli',
    slug: 'rangoli',
    description:
      'Three sisters return to their ancestral home in Pune for Diwali and must decide whether to sell the house that raised them.',
    durationMinutes: 128,
    genres: ['Family', 'Drama'],
    languages: ['Hindi', 'Marathi'],
    releaseOffsetDays: -15,
    certificate: 'U',
    director: 'Sai Deshpande',
    cast: ['Radhika Pawar', 'Mrunal Joshi', 'Sneha Kulkarni'],
  },
  {
    title: 'Shadow Protocol',
    slug: 'shadow-protocol',
    description:
      'An intelligence analyst discovers her own name on a kill list and has 48 hours to find out who wrote it.',
    durationMinutes: 141,
    genres: ['Action', 'Spy'],
    languages: ['English', 'Hindi', 'Tamil'],
    releaseOffsetDays: -3,
    certificate: 'A',
    director: 'Rohan Saxena',
    cast: ['Zara Khan', 'Michael Stone', 'Arun Prakash'],
  },
  {
    title: 'Little Big Paws',
    slug: 'little-big-paws',
    description:
      'A street puppy from Chennai sets out across the city to find the girl who once shared her lunch with him.',
    durationMinutes: 98,
    genres: ['Animation', 'Family'],
    languages: ['English', 'Hindi'],
    releaseOffsetDays: -10,
    certificate: 'U',
    director: 'Anita Rao',
    cast: ['Voice: Tara Singh', 'Voice: Kabir Das'],
  },
  {
    title: 'Veera',
    slug: 'veera',
    description:
      'In 14th-century Vijayanagara, a farmer’s daughter rises to command the army that will defend the empire’s last fort.',
    durationMinutes: 172,
    genres: ['Action', 'Period'],
    languages: ['Telugu', 'Hindi', 'Kannada'],
    releaseOffsetDays: -1,
    certificate: 'UA',
    director: 'K. Srinivas',
    cast: ['Anushka Rao', 'Teja Varma', 'Sudhir Gowda'],
  },
  {
    title: 'Echoes of Dawn',
    slug: 'echoes-of-dawn',
    description: 'Two strangers keep missing each other at the same Bengaluru café — until the day the café closes.',
    durationMinutes: 117,
    genres: ['Romance', 'Drama'],
    languages: ['English'],
    releaseOffsetDays: -25,
    certificate: 'U',
    director: 'Leah Fernandes',
    cast: ['Aditya Bose', 'Kiara Menon'],
  },
  {
    title: 'Neon Nights',
    slug: 'neon-nights',
    description: 'A getaway driver in a rain-soaked future Mumbai takes one last job that turns out to be a rescue.',
    durationMinutes: 136,
    genres: ['Action', 'Sci-Fi'],
    languages: ['Hindi', 'English'],
    releaseOffsetDays: 14,
    certificate: 'A',
    director: 'Imran Qureshi',
    cast: ['Rehan Qadri', 'Aliya Sen'],
  },
  {
    title: 'Mission Gaganyaan',
    slug: 'mission-gaganyaan',
    description: 'The untold story of the engineers who put India’s first crew into orbit.',
    durationMinutes: 150,
    genres: ['Drama', 'Biopic'],
    languages: ['Hindi', 'English', 'Tamil'],
    releaseOffsetDays: 30,
    certificate: 'U',
    director: 'Shreya Natarajan',
    cast: ['Vidya Bhat', 'Akash Kulkarni', 'Nithya Murali'],
  },
];

/** ownerIndex refers to the partner order in `users`. */
const theatres = [
  {
    name: 'Galaxy Cinemas',
    address: '100 Feet Road, Indiranagar',
    city: 'Bengaluru',
    phone: '+91 80 4000 1000',
    email: 'galaxy.indiranagar@example.com',
    screens: 3,
    status: 'approved',
    ownerIndex: 0,
  },
  {
    name: 'Starlight Multiplex',
    address: '80 Feet Road, Koramangala',
    city: 'Bengaluru',
    phone: '+91 80 4000 2000',
    email: 'starlight.koramangala@example.com',
    screens: 2,
    status: 'approved',
    ownerIndex: 0,
  },
  {
    name: 'Orbit Screens',
    address: 'Road No. 12, Banjara Hills',
    city: 'Hyderabad',
    phone: '+91 40 4000 3000',
    email: 'orbit.banjara@example.com',
    screens: 2,
    status: 'approved',
    ownerIndex: 0,
  },
  {
    name: 'Cineplex Gachibowli',
    address: 'Financial District, Gachibowli',
    city: 'Hyderabad',
    phone: '+91 40 4000 4000',
    email: 'cineplex.gachibowli@example.com',
    screens: 2,
    status: 'approved',
    ownerIndex: 1,
  },
  {
    name: 'Marine Drive Talkies',
    address: 'Netaji Subhash Chandra Bose Road, Churchgate',
    city: 'Mumbai',
    phone: '+91 22 4000 5000',
    email: 'marinedrive@example.com',
    screens: 2,
    status: 'approved',
    ownerIndex: 1,
  },
  {
    name: 'Marina Cinemas',
    address: 'Kamarajar Salai, Mylapore',
    city: 'Chennai',
    phone: '+91 44 4000 6000',
    email: 'marina.mylapore@example.com',
    screens: 1,
    status: 'approved',
    ownerIndex: 1,
  },
  {
    name: 'Sunrise Theatre',
    address: 'FC Road, Shivajinagar',
    city: 'Pune',
    phone: '+91 20 4000 7000',
    email: 'sunrise.pune@example.com',
    screens: 1,
    status: 'pending',
    ownerIndex: 0,
  },
  {
    name: 'Old Town Pictures',
    address: 'MG Road, Camp',
    city: 'Pune',
    phone: '+91 20 4000 8000',
    email: 'oldtown.pune@example.com',
    screens: 1,
    status: 'blocked',
    statusReason: 'Fire safety certificate expired',
    ownerIndex: 1,
  },
];

/** Daily start times in IST (HH:mm). Spaced so even the longest film plus cleaning fits. */
const SHOW_TIMES = ['10:00', '13:30', '17:00', '20:45'];

module.exports = { users, movies, theatres, SHOW_TIMES };
